version: "3.9"

services:
  dup:
    image: "xtonousou/dup:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dup.env:/app/dup.env:ro"
      - "./dup.creds.env:/app/dup.creds.env:ro"
    restart: "unless-stopped"
