version: "3.9"

services:
  dup:
    image: "xtonousou/dup:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./dup.env:/app/dup.env"
      - "./dup.creds.env:/app/dup.creds.env"
